### ISSUE TITLE
some packet content is displayed wrong

### ISSUE THREAD

**Issue by JanCantCode** [aridevelopment-de/fabric-packet-logger#24] opened 2023-05-11 11:56 UTC
# issue
when clicking on a packet, in this case a setContainerContent packet, the contents actually belong to a particle spawn packet. 

# example

![image](https://github.com/aridevelopment-de/fabric-packet-logger-frontend/assets/91028774/117e8267-7d78-4a3f-90d1-5df930da8344)

![image](https://github.com/aridevelopment-de/fabric-packet-logger-frontend/assets/91028774/6b02cd3b-6b74-4111-9bee-fca410aa3ed3)

i have attempted reloading etc.

**Comment by Ari24-cb24** [comment] 2023-05-11 11:58
I also noticed that yesterday, seems like I have messed up some indecies. If you still wan't to inspect the actual data, I recommend using the export feature since this always exports the saved data and not what is displayed on the frontend.

Will investigate

**Comment by JanCantCode** [comment] 2023-05-11 12:07
oh alright, thanks for the answer.

do the exportable logs also care about blacklists / whitelists?


also the mod now made me unable to join any server with seemingly random kick messages
https://cdn.discordapp.com/attachments/669557283767844894/1106189544455405648/image.png
https://cdn.discordapp.com/attachments/669557283767844894/1106189545021636659/image.png
https://cdn.discordapp.com/attachments/669557283767844894/1106189544790966343/image.png

**Comment by Ari24-cb24** [comment] 2023-05-11 12:08
> do the exportable logs also care about blacklists / whitelists?  

Generally, yes

> also the mod now made me unable to join any server with seemingly random kick messages

Seems weird, is probably a serialization error. Mind sharing some console errors from your client?

**Comment by JanCantCode** [comment] 2023-05-11 12:12
the issue seems to have resolved itsself after several restarts. but no errors appeared in the latest.log when getting kicked btw

**Comment by Ari24-cb24** [comment] 2023-05-11 12:14
Interesting, will try to reproduce it / fix it later. I do have some ideas where to start already though.

**Comment by Ari24-cb24** [comment] 2023-05-11 12:17
Also @JanCantCode (forgot to ask), which version of minecraft and packetlogger are you using?

**Comment by JanCantCode** [comment] 2023-05-11 12:21
the newest release, 1.19.4

**Comment by JanCantCode** [comment] 2023-05-11 12:21
(from modrinth)

**Comment by Ari24-cb24** [comment] 2023-05-11 12:54
Thanks.

So from what I can tell is that most likely
- Invalid Payload register is caused by another mod. Since packetlogger doesn't modify/send any payload on startup, it's unlikely that this has been caused by PacketLogger
- Registry error should now be fixed
- IndexOutOfBounds may be fixed now

I will publish a new version in a bit with those fixes and improved error logging. If any of those errors should happen again, the console will contain more useful information.

**Comment by Ari24-cb24** [comment] 2023-05-11 13:15
I noticed something odd with the registry error now. I think the problem is more fundamental than I anticipated. Will first analyze this further before publishing a new version.

**Comment by Ari24-cb24** [comment] 2023-05-12 07:07
Should now be fixed in 1.6.1
- Release: https://github.com/aridevelopment-de/fabric-packet-logger/releases/tag/1.6.1%2B1.19.4
- Modrinth: https://modrinth.com/mod/packetlogger/version/1.6.1

**Closed as completed by Ari24-cb24** 2023-05-12 07:07 UTC
